---
apiVersion: actions.github.upbound.io/v1alpha1
kind: ActionsSecret
metadata:
  name: kubeconfig-previews
spec:
  forProvider:
    plaintextValueSecretRef:
      key: kubeconfig
      name: previews-cluster
      namespace: infra
    repository:
      name: devopsparadox/silly-demo
    secretName: KUBECONFIG_PREVIEWS
