---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: previews
  namespace: infra
spec:
  id: previews
  compositionSelector:
    matchLabels:
      provider: civo
      cluster: ck-all
  parameters:
    nodeSize: medium
    minNodeCount: 1
